version: '3.8'

services:
  app:
    container_name: laboratorie-xams-app
    build: .
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
  
  db:
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}